spring.datasource.url=jdbc:postgresql://localhost:5432/banking_db
spring.datasource.username=postgres
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=mySecretKeyForJWTTokenGeneration123456789
jwt.expiration=86400000

zmkzkgaDKlIgZ9CtS6uN2DWg9N5DkvDX

postgresql://neovault_db_user:zmkzkgaDKlIgZ9CtS6uN2DWg9N5DkvDX@dpg-d8m49nb7uimc73elrrl0-a.singapore-postgres.render.com/neovault_db